# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing demo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -vs --html="report1.html"
    - name: Commit Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "vidyagowda005@gmail.com"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
    - name: commiting the files
      # executing the steps irrespective of the status of previous step
      if: ${{ always() }}
      run: |
        git config --global user.name "vidyagowda159"
        git config --global user.email "vidyagowda005@gmail.com"
        git add -A
        git diff-index --quiet HEAD
        git commit -m "updated logs"
    - name: pushing changes
      if: ${{ always() }}
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: master